import dotenv from 'dotenv';

dotenv.config();

export const PROJECT_ID = process.env.PROJECT_ID;
export const LOCATION = process.env.LOCATION;
export const MODEL = process.env.MODEL;

export const VALID_STATES = [
    'UTTAR PRADESH',
    'MADHYA PRADESH',
    'TAMIL NADU',
    'MANIPUR',
    'MIZORAM',
    'TRIPURA',
    'KERALA',
    'ODISHA',
    'ANDHRA PRADESH',
    'PUNJAB',
    'WEST BENGAL',
    'JAMMU AND KASHMIR',
    'ASSAM',
    'DELHI',
    'HIMACHAL PRADESH',
    'UTTARAKHAND',
    'GUJARAT',
    'GOA',
    'JHARKHAND',
    'CHHATTISGARH',
    'MAHARASHTRA',
    'NAGALAND',
    'BIHAR',
    'ARUNACHAL PRADESH',
    'KARNATAKA',
    'MEGHALAYA',
    'SIKKIM',
    'HARYANA',
    'PUDUCHERRY',
    'TELANGANA'
];
  

export const VALID_CROPS = [
    'BAJRA',
    'COTTON(LINT)',
    'GROUNDNUT',
    'JOWAR',
    'MAIZE',
    'RICE',
    'SANNHAMP',
    'SESAMUM',
    'SMALL MILLETS',
    'SOYABEAN',
    'SUGARCANE',
    'BARLEY',
    'GRAM',
    'LINSEED',
    'POTATO',
    'RAPESEED &MUSTARD',
    'TURMERIC',
    'WHEAT',
    'SUNFLOWER',
    'BANANA',
    'DRY CHILLIES',
    'GARLIC',
    'GUAR SEED',
    'ONION',
    'SWEET POTATO',
    'TOBACCO',
    'ARHAR/TUR',
    'CASTOR SEED',
    'HORSE-GRAM',
    'JUTE',
    'MESTA',
    'MOONG(GREEN GRAM)',
    'NIGER SEED',
    'OTHER KHARIF PULSES',
    'URAD',
    'MASOOR',
    'OTHER RABI PULSES',
    'OTHER CEREALS',
    'PEAS & BEANS (PULSES)',
    'SAFFLOWER',
    'CORIANDER',
    'GINGER',
    'ARECANUT',
    'BLACK PEPPER',
    'CARDAMOM',
    'CASHEWNUT',
    'COCONUT',
    'RAGI',
    'TAPIOCA',
    'COWPEA(LOBIA)',
    'OTHER OILSEEDS',
    'OILSEEDS TOTAL',
    'KHESARI',
    'MOTH',
    'OTHER SUMMER PULSES'
];
  